# Generated by Django 5.1.2 on 2025-02-07 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='flower',
            new_name='item',
        ),
    ]
