# Generated by Django 5.1.2 on 2024-10-18 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0002_cart_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='flower',
            name='category',
        ),
        migrations.RemoveField(
            model_name='flowerimage',
            name='flower',
        ),
        migrations.AddField(
            model_name='flowerimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='flower',
            name='categories',
            field=models.ManyToManyField(related_name='flowers', to='flowers.category'),
        ),
    ]
