# Generated by Django 5.1.2 on 2024-11-01 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0008_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='flower_images/'),
        ),
        migrations.AlterField(
            model_name='flowerimage',
            name='image',
            field=models.ImageField(upload_to='flower_images/extra_images/'),
        ),
    ]
