# Generated by Django 5.1.2 on 2024-11-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0009_alter_flower_image_alter_flowerimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='flowerimage',
            name='image',
            field=models.ImageField(upload_to='flower_images'),
        ),
    ]
