# Generated by Django 5.1.2 on 2024-11-07 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0010_alter_flower_image_alter_flowerimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_number',
        ),
        migrations.AlterField(
            model_name='flower',
            name='image',
            field=models.ImageField(blank=True, default='default_image.png', null=True, upload_to='flower_images/'),
        ),
    ]
