# Generated by Django 5.1.2 on 2024-11-09 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowers', '0012_profile_order_updates_profile_promotions_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
